services:
  - name: whisper-frontend
    type: web
    runtime: static
    rootDir: whisper-frontend
    buildCommand: npm install && npm run build
    publishDir: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://whisper-backend.onrender.com

  - name: whisper-backend
    type: web
    runtime: elixir
    rootDir: whisper_transcriber
    region: ohio
    plan: free
    buildCommand: |
      mix deps.get
      mix compile
      python3 -m venv .venv
      . .venv/bin/activate
      pip install -r requirements.txt
    startCommand: mix phx.server
    envVars:
      - key: MIX_ENV
        value: prod
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PORT
        value: "10000"
    healthCheckPath: /health
