services:
  - name: whisper-frontend
    type: web
    runtime: static
    rootDir: whisper-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: REACT_APP_API_URL
        value: https://whisper-backend-4x0h.onrender.com

  - name: whisper-backend
    type: web
    runtime: elixir
    rootDir: whisper_transcriber
    plan: free
    buildCommand: |
      mix deps.get
      mix compile
      python3 -m venv .venv
      . .venv/bin/activate
      pip install -r requirements.txt
      mkdir -p priv/uploads
      chmod 777 priv/uploads
    startCommand: iex -S mix
    envVars:
      - key: MIX_ENV
        value: prod
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: PORT
        value: "10000"
    healthCheckPath: /health
    # Add memory limit and scaling options
    scaling:
      minInstances: 1
      maxInstances: 1
    resources:
      limits:
        memory: 1024 # Set to 1GB
      requests:
        memory: 512 # Request 512MB minimum